package edu.ucr.cnc.cas.support.duo.authentication.principal;

import javax.validation.constraints.NotNull;
import org.jasig.cas.authentication.principal.Credentials;

/**
 * DuoCredentials implements the {@link Credentials} interface and stores the signed duo response from the
 * javascript routine on the login page that can then be verified via the {@link edu.ucr.cnc.cas.duo.authentication.handler.DuoAuthenticationHandler}
 * authentication handler.
 *
 * @author Michael Kennedy <michael.kennedy@ucr.edu>
 * @version 1.0
 */
public class DuoCredentials implements Credentials {

    private static final long serialVersionUID = -2938374687263928372L;

    /**
     * The response from Duo
     */
    @NotNull
    private String signedDuoResponse;

    /**
     * Getter method for signedDuoResponse
     *
     * @return a String containing the signed Duo response generated by the Duo web service
     */
    public String getSignedDuoResponse() {
        return signedDuoResponse;
    }

    /**
     * Setter method for signedDuoResponse
     *
     * @param signedDuoResponse a String containing the signed Duo response generated by the Duo web service
     */
    public void setSignedDuoResponse(String signedDuoResponse) {
        this.signedDuoResponse = signedDuoResponse;
    }
}
